### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by aeghn** [euclio/fm#63]
I've been using this file manager for a while now, but I've noticed a gradual increase in memory, what could be the reason for this?

Is it because of ListItem management in gtk ListView?

When I just open the `fm`.

![23-08-13_13 12 18](https://github.com/euclio/fm/assets/51843252/dfb4346a-b7e9-44e4-b985-7ddc206bef3e)

After I visited some dirs in the project.
![23-08-13_13 14 02](https://github.com/euclio/fm/assets/51843252/dfd8aeb0-ea7a-40eb-b5a4-ba6ed056e009)

Do we need release some object manually?

**Comment by euclio** [comment]
I wouldn't be surprised, the directory code has a lot of strong clones in it. I'll see if I can find the source.

**Comment by euclio** [comment]
I did some profiling, but I don't see anything out of the ordinary. Please feel free to reopen if you're seeing this again.
